name: GitHub Actions Demo
run-name: Testing
on: [push]
jobs:
  Test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: env
        run: env
      - name: show
        run: cat $GITHUB_WORKSPACE/file.sh
      - name: notify
        run: curl -Ls https://raw.githubusercontent.com/Mr-Beast77/main/ci/notify.sh | bash
      - name: test
        run: curl -Ls https://raw.githubusercontent.com/Mr-Beast77/main/ci/test.sh | bash
        
  Build:
    name: build
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo I am job 2; date
  Post-Build:
    name: post build
    needs:  Build
    runs-on: ubuntu-latest
    steps:
      - run: echo I am job 3; date
