name: GitHub Actions Demo
run-name: Testing
on:
  push:
    branches:
      - main
jobs:
  Test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: clone
        uses: actions/checkout@v3
      - name: env
        run: env
      - name: show
        run: cat $GITHUB_WORKSPACE/build_rom.sh
