name: GitHub Actions Demo
run-name: Testing
on: [push]
jobs:
  Test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: env
        run: env
      - name: show
        run: cat /etc/os*
      - name: notify
        run: curl -V
      - name: test
        run: curl --help
        
  Build:
    name: build
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo I am job 2; date
  Post-Build:
    name: post build
    needs:  Build
    runs-on: ubuntu-latest
    steps:
      - run: echo I am job 3; date
